### ISSUE TITLE
I didn't see the P2P part in this copy of bitcoin sourcecode.

### ISSUE THREAD

**Issue by cdhit** [trottier/original-bitcoin#1]
RT.

**Comment by Pegasus2121** [comment]
Pegasus2121

**Comment by ymmah** [comment]
посмотреть RT и узнать, кого мы собираемся взломать. 
следующий

觀看RT並找出我們計劃破解的對象。 下一個


觀  see, observe, view; appearance
看  look, see; examine, scrutinize
RT
並 equal to; side by side; also, what is more; both
找 search, seek, look for; find
出 go out, send out; stand; produce
我 our, us, i, me, my, we
們 adjunct pronoun indicate plural
計 plan, plot; strategem; scheme
劃 divide, mark off, lay boundary
破 break, ruin, destroy; rout
解 loosen, unfasten, untie; explain
的 possessive, adjectival suffix
對 correct, right; facing, opposed
象 elephant; ivory; figure, image
下 under, underneath, below; down; inferior; bring down
一 one; a, an; alone
個 numerary adjunct, piece; single

(( Guānkàn RT bìng zhǎo chū wǒmen jìhuà pòjiě de duìxiàng. Xià yīgè ))

**Comment by ymmah** [comment]
問題更多
